### ISSUE TITLE
async requests

### ISSUE THREAD

**Issue by matryer** [veritone/engine-toolkit#6]
Some engines perform long running tasks, and people have asked if there's a way to have the engine toolkit periodically check for completion.

**Comment by matryer** [comment]
@dahernan and I think the right solution for this is:

* 3rd party engine code returns [102 Processing status code](https://httpstatuses.com/102) to indicate that the task was accepted. The webhook will have a new field called `postbackComplete` which is a URL to which they should post the results when ready. This endpoint will encode all the necessary state that the toolkit requires to send the response to the platform.
* When the task is finished, the 3rd party engine code makes a `POST` request, the body of which contains the results

**Comment by satya-ip** [comment]
I think this is a good approach. We have implemented a similar approach for one of our customers with a minor difference. When a request submitted, the service returns [202 Processing status code](https://httpstatuses.com/202) and for the further check for results returns [102 Processing status code](https://httpstatuses.com/102). In your case, since you are supplying _postbackComplete_, there is no need for two status codes.

**Comment by matryer** [comment]
Thanks for your comments. We’ll have a word with the team next week and get this scheduled.

**Comment by matryer** [comment]
After more investigation, the use case was better served by a different approach.

**Comment by matryer** [comment]
Apologies for a bad answer. The other approach I mentioned was an undocumented API where results can be posted at a later date. This is out of scope for the Engine Toolkit project and will be discussed elsewhere.
